import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import React from "react";
import style from "../../../styles/pages/Login.module.scss"
import LeftColumn from "@/components/molecules/LeftColumnLogReg";

const Recruiter = () => {
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [isLoading, setIsLoading] = React.useState(false);
  const [error, setError] = React.useState(null);

  const handleSubmit = async () => {
    try {
      setIsLoading(true);

      const connect = await axios.post("/api/login", {
        email,
        password,
      });

      setIsLoading(false);
      setError(null);

      if(!connect?.data?.data?.recruiter_id){
        localStorage.setItem("token", connect?.data?.token);
        localStorage.setItem("profile", JSON.stringify(connect?.data?.data));
      } else {
        setError("Only Talents can login here")
      }
    } catch (error) {
      setIsLoading(false);
      setError('Something wrong in our server');
    }
  };

  return (
    <>
    <Head>
        <title>Talent Login | Proworld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={style.main}>
      <div className="row">
        <div className={"col-lg-6"}>
          <LeftColumn />
        </div>
        <div className="col-lg-6">
          <div className={style.loginForm}>
            <div className={style.rightCol}>
              <h2>Hello, Talent !</h2>
              <p className={error ? "mb-3" : "mb-5"}>
                Login to start your session
              </p>

              {error && (
                <div class="alert alert-danger mb-3" role="alert">
                  {error}
                </div>
              )}

              <form>
                <div className="mb-3">
                  <label htmlFor="exampleInputEmail1" className="form-label">
                    Email
                  </label>
                  <input
                    type="email"
                    className="form-control form-control-lg"
                    id="exampleInputEmail1"
                    aria-describedby="emailHelp"
                    placeholder="Type your email"
                    onChange={(e) => setEmail(e.target.value)}
                  />
                </div>
                <div className="mb-4">
                  <label htmlFor="exampleInputPassword1" className="form-label">
                    Password
                  </label>
                  <input
                    type="password"
                    className="form-control form-control-lg"
                    id="exampleInputPassword1"
                    placeholder="Type your password"
                    onChange={(e) => setPassword(e.target.value)}
                  />
                </div>
                <div class="d-grid mb-3">
                  <button
                    type="submit"
                    className="btn btn-primary btn-lg"
                    onClick={handleSubmit}
                    disabled={isLoading}
                  >
                    {isLoading ? "Loading..." : "Login"}
                  </button>
                </div>

                <p className="text-center">
                You don't have an account yet?{" "}
                  <Link href="/auth/register">Register here</Link>
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </main>
    </>
  );
}

export default Recruiter;

// css module
