import React, { useState } from "react";
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "@/components/organisms/Navbar";
import Footer from "@/components/organisms/Footer";
import { TfiLocationPin } from "react-icons/tfi";
import mailLogo from "@/public/images/mail-logo.png";
import instaLogo from "@/public/images/instagram.svg";
import githubLogo from "@/public/images/github-logo.svg";
import gitlabLogo from "@/public/images/gitlab-logo.svg";
import Image from "next/image";
import styles from "@/styles/pages/Slug.module.scss";
import Link from "next/link";
import { useSelector } from "react-redux";

const ProfileDetail = (props) => {
  const { profile } = props;

  const talent = profile?.data?.[0]?.user;
  const skills = JSON.parse(profile?.data?.[0]?.skills);
  const portfolio = profile?.data?.[0]?.portfolios;
  const workExperience = profile?.data?.[0]?.work_experiences;

  const profileStalker = useSelector((state) => state.auth);

  const isRecruiter = profileStalker?.profile?.payload?.recruiter_id;

  const router = useRouter();

  const {
    query: { id },
  } = router;

  return (
    <>
      <Head>
        <title>
          {talent?.fullname?.charAt(0).toUpperCase() +
            talent?.fullname?.slice(1)}{" "}
          | Proworld
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ background: "#E5E5E5" }}>
        <Navbar />
        <div
          style={{
            background: "transparent",
            paddingTop: "10%",
            paddingBottom: "4.5%",
          }}
        >
          <div
            className={`container ${styles.containerContent}`}
            style={{ background: "white", borderRadius: "4px" }}
          >
            <div
              style={{
                backgroundColor: "#5e50a1",
                height: "210px",
                borderTopRightRadius: "4px",
                borderTopLeftRadius: "4px",
              }}
            >
              <div>
                <img
                  src={talent?.photo_profile}
                  // src={"https://www.its.ac.id/international/wp-content/uploads/sites/66/2020/02/blank-profile-picture-973460_1280.jpg"}
                  style={{
                    width: "170px",
                    marginLeft: "92px",
                    marginTop: "116px",
                    borderRadius: "50%",
                  }}
                  alt="Profile"
                />
              </div>
            </div>
            <div style={{ marginTop: "94px", marginLeft: "95px" }}>
              <h2>
                {/* {profile?.["user.fullname"]?.charAt(0)?.toUpperCase() +
                  profile?.["user.fullname"]?.slice(1)} */}
                {talent?.fullname?.charAt(0).toUpperCase() +
                  talent?.fullname?.slice(1)}
              </h2>
              <p style={{ marginTop: "15px" }}>
                {profile?.data?.[0]?.job.charAt(0).toUpperCase() +
                  profile?.data?.[0]?.job.slice(1)}
              </p>
              <div
                className="d-flex"
                style={{ marginBottom: "-6px", gap: "8px" }}
              >
                <TfiLocationPin />
                <p style={{ marginTop: "-5px", color: "#9EA0A5" }}>
                  {/* {profile?.domicile?.charAt(0).toUpperCase() +
                    profile?.domicile?.slice(1)} */}
                  {profile?.data?.[0]?.domicile.charAt(0).toUpperCase() +
                    profile?.data?.[0]?.domicile.slice(1)}
                </p>
              </div>
              <div>
                <p style={{ color: "#9EA0A5", width: "90%" }}>
                  {profile?.data?.[0]?.description?.charAt(0).toUpperCase() +
                    profile?.data?.[0]?.description?.slice(1)}
                </p>
              </div>
              <div className="d-flex">
                <h6 className="me-1" style={{ color: "rgb(158, 160, 165)" }}>
                  {" "}
                  Lasted work at
                </h6>
                <h6>
                  {profile?.data?.[0]?.company.charAt(0).toUpperCase() +
                    profile?.data?.[0]?.company.slice(1)}
                </h6>
              </div>
              <div>
                {isRecruiter !== 0 && (
                  <button
                    className="btn btn-primary"
                    style={{ width: "33%", height: "55px", marginTop: "12px" }}
                    onClick={() => {
                      router.replace(`/jobs/hire/${id}`);
                    }}
                  >
                    Hire
                  </button>
                )}
              </div>
              <div>
                <h2 style={{ marginTop: "30px" }}>Skill</h2>
                <div className="d-flex" style={{ width: "90%" }}>
                  {skills.length > 0 ? (
                    <div className="row">
                      {skills.map((item, key) => (
                        <div
                          style={{ flex: "0 0 auto", width: "31%" }}
                          key={key}
                        >
                          <span
                            className={"badge bg-warning"}
                            style={{
                              marginTop: "10px",
                              marginRight: "12px",
                              height: "40px",
                              width: "95px",
                              padding: "13px",
                            }}
                          >
                            {item}
                          </span>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <h5 className="mt-4">
                      {talent?.fullname?.charAt(0).toUpperCase() +
                        talent?.fullname.slice(1)}{" "}
                      doesn't have any skills yet
                    </h5>
                  )}
                </div>
              </div>
              <div>
                <div style={{ display: "flex", marginTop: "35px" }}>
                  <Image
                    src={mailLogo}
                    alt="Mail"
                    style={{ width: "47px", height: "40px", marginTop: "6px" }}
                  />
                  <p
                    style={{
                      marginTop: "10px",
                      marginLeft: "20px",
                      color: "#9EA0A5",
                    }}
                  >
                    {talent?.fullname.toLowerCase().split(" ").join("")}
                    @gmail.com
                  </p>
                </div>
                <div style={{ display: "flex", marginTop: "12px" }}>
                  <Image
                    unoptimized={true}
                    src={instaLogo}
                    alt="Instagram"
                    style={{ width: "50px", height: "40px" }}
                  />
                  <p
                    style={{
                      marginTop: "7px",
                      marginLeft: "20px",
                      color: "#9EA0A5",
                    }}
                  >
                    {talent?.fullname.toLowerCase().split(" ").join("")}_
                  </p>
                </div>
                <div style={{ display: "flex", marginTop: "12px" }}>
                  <Image
                    unoptimized={true}
                    src={githubLogo}
                    alt="Github"
                    style={{ width: "50px", height: "40px" }}
                  />
                  <p
                    style={{
                      marginTop: "7px",
                      marginLeft: "20px",
                      color: "#9EA0A5",
                    }}
                  >
                    {talent?.fullname.toLowerCase().split(" ").join(".")}
                  </p>
                </div>
                <div style={{ display: "flex", marginTop: "12px" }}>
                  <Image
                    unoptimized={true}
                    src={gitlabLogo}
                    alt="Gitlab"
                    style={{ width: "50px", height: "40px" }}
                  />
                  <p
                    style={{
                      marginTop: "7px",
                      marginLeft: "20px",
                      color: "#9EA0A5",
                    }}
                  >
                    {talent?.fullname.toLowerCase().split(" ").join(".")}
                  </p>
                </div>
              </div>
              <div
                style={{
                  marginTop: "45px",
                  paddingTop: "30px",
                  paddingBottom: "30px",
                }}
              >
                <ul className="nav nav-tabs">
                  <li className="nav-item">
                    <button
                      className="nav-link text-dark"
                      id="nav-portfolio-tab"
                      data-bs-toggle="tab"
                      data-bs-target="#nav-portfolio"
                      type="button"
                      role="tab"
                      aria-controls="nav-portfolio"
                      aria-selected="true"
                    >
                      Portfolio
                    </button>
                  </li>
                  <li className="nav-item">
                    <button
                      className="nav-link text-dark"
                      id="nav-experience-tab"
                      data-bs-toggle="tab"
                      data-bs-target="#nav-experience"
                      type="button"
                      role="tab"
                      aria-controls="nav-experience"
                      aria-selected="false"
                    >
                      Work Experience
                    </button>
                  </li>
                </ul>
                <div className="tab-content" id="nav-tabContent">
                  <div
                    className="tab-pane fade show"
                    id="nav-portfolio"
                    role="tabpanel"
                    aria-labelledby="nav-portfolio-tab"
                  >
                    <div className="row">
                      {portfolio.length > 0 ? (
                        portfolio.map((item, key) => (
                          <div className="col-3" key={key}>
                            {/* <a
                              target="_blank"
                              href={item?.link}
                              rel="noopener noreferrer"
                              style={{ color: "white" }}
                            > */}
                            <img
                              src={
                                item?.photo === "belanja app"
                                  ? "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAeFBMVEUAAAD////8/Pzy8vLg4OApKSmzs7M/Pz8iIiLt7e3X19f19fVXV1c7Ozvw8PCHh4c1NTWVlZVlZWVwcHBgYGDAwMDIyMhRUVGLi4vOzs57e3tJSUlbW1t3d3dERESkpKQMDAwZGRmfn58uLi4UFBSUlJStra0dHR2J6hNlAAAE30lEQVR4nO2d6XayMBCGCeCC4IbFtVVrv7b3f4cfSFd7lHkhMCaZ53fLyTyd7Eu9+NETSCSxJ67IJNwFEARBEARBENqlt0/Sp+l0vV0sksFseOQuz70yeOpvQl/9JAhH2Tzdv3MX7b7YT5ehuko06qdj7iLeCavDDVFKlcnmh4fkH3dJuRm/3jT105eKsvTIXV5G0qV/W9OFLhUdVtxlZmJLSKq/jBbc5WZgGtVRVaRYOOUue8esc1U+sQ5e6Mp/K3JJVxp+pUmt3MqzK+WOoSNmyzqSLsmG3HF0wTrW4Uqp+Ik7ktbpbeo2Vhfk38i4g2mZbazJVdkvWj0LynRo+kFs7xh1HNbrAK+S56itvWIa59FptVV8bMsdVitMP8PTjI0D1FMrpgrsmyy+taUqr9i2nT4oXOltr37Iinvc4Wnl0Iamb0Lu+HQybymrvjhwR6iPbWtt+wcWNVuJr3QPsC5dWVMRX6KW8+rMK3eYeth04UrFR+44dTDvwFTBiTtQDeyKJkVSi8aoA08la+5QGzPtJKvORNyxNuV50p0s9cAdbUNObQ/dv/FVnzvaZgw1beTQCLjDbcapw0qoDK+Hxw4Tq/irGD2dbn0C/cuWr0bcATeBPsYquoG/XlHTJo9LZ0C0ha14eVjsxsPeePBwymqdsjH4IuCJHmWxF3/RPK/6qCqjt8WQmU728vf3h/BUydzJ9DsxwmLH4UqnjybXstsINbIgt9Dh87VvZFgjb+56KTktoquuPC9AXBk8l94QIwxuHeFLIVnBsavgdBMQ+n6/8hxMhOx1xKYenXymRFd9fG+OLLTGs25i086OFp8/uP2ZITKQr/rY3ULqDH21qfoOcrfAWFlTUnTVp6uQ0YNv6hlT2hZYdXgHQJaxbVaxolzNpPI7W0SWqWePegMC++p680BWlY+zbgxvnYDYq56pzlPLGQCyzJ3uaAKRZe5EWhMroIG3/TJPJaTx2gfmLv5pAlkANHhZWQ/IdMfea080HhV9Jm34/n1z6M8ZGL7JqgGgeffVnLu0vKzornKsOQxfiz2wt+M7Pn5PkMtRvtujrHWhii7L2JU/HWSYK4O3oxuTTqAqqFxu3qFTDsWSa/XOh60sJoir8g7HnrvQPLxn8EE2X71xl5qHBXYYpHTl6LJfv9apXScr4SysdenVxocwKnkMyq4NxMkGa1Hv2LyTS+/bOg9lODp0T/0a7ZWjrvaxtFdkRucxAzAfPP+o+Zd964De4zwn4cTgCygNGKN39AtXG0ff1e/jHaHvZhX0vBf8HufG2ZVR5ERDed3H1bTy6NcxPlmaenpUAz1sWWZi/7PKN3iEXLnxYPdVgKeQnN+l95AX4h1u2UuAC76u55V3pB8scnKN4Rc94pA0nxLtuMvKzoyYVg5vpX6zJ9dCpwdYJTvqOlbg8MD9k4SaWI7upf6CPICXJgu4Jmf0C1maIL/e4Pzo3QNkOX/fxDvf1Kdh37+rwBFZAKs+EZnsCIIgCIIgCIIg2MvwpUeDu6D3wDKeBBRCt4+ElFC37yORVciibYWJLE8yC0JkAYgsAJEFILIARBaAyAIQWQAiC0BkAYgsAJEFILIARBaAyAIQWQAiC0BkAYgsAJEFILIARBZAFtLYiCxBEARBEARBEARBMA03n92tReLFYotIEvwHq2g+/aq2ZzgAAAAASUVORK5CYII="
                                  : item?.photo
                              }
                              style={{
                                width: "175px",
                                height: "100px",
                                marginTop: "35px",
                                padding: "1px",
                                border: "2px solid #5E50A1",
                                objectFit: "cover",
                              }}
                              alt="Project"
                            />
                            {/* </a> */}
                            <p
                              style={{
                                textAlign: "center",
                                paddingRight: "60px",
                                paddingTop: "5px",
                              }}
                            >
                              {item?.name}
                            </p>
                          </div>
                        ))
                      ) : (
                        <h4 className="mt-5 mb-5">
                          {talent?.fullname?.charAt(0).toUpperCase() +
                            talent?.fullname.slice(1)}{" "}
                          doesn't have a portfolio yet
                        </h4>
                      )}
                    </div>
                  </div>
                  <div
                    className="tab-pane fade show"
                    id="nav-experience"
                    role="tabpanel"
                    aria-labelledby="nav-experience-tab"
                  >
                    {workExperience.length > 0 ? (
                      workExperience.map((item, key) => (
                        <>
                          <div
                            style={{ display: "flex", marginTop: "35px" }}
                            key={key}
                          >
                            <div>
                              <img
                                src={
                                  item?.photo ??
                                  "https://img.freepik.com/free-vector/thoughtful-woman-with-laptop-looking-big-question-mark_1150-39362.jpg?w=2000"
                                }
                                style={{
                                  width: "120px",
                                  marginRight: "35px",
                                  borderRadius: "5px",
                                }}
                                alt="Company"
                              />
                            </div>
                            <div style={{ width: "76%" }}>
                              <h3>{item?.position}</h3>
                              <h6>{item?.company}</h6>
                              <p style={{ color: "#9EA0A5" }}>
                                {/* 7 July 2021 - 1 January 2022 • 6 Months */}
                                {item?.date}
                              </p>
                              <p>{item?.description}</p>
                            </div>
                          </div>
                          <hr style={{ width: "91%" }} />
                        </>
                      ))
                    ) : (
                      <h4 className="mt-5 mb-5">
                        {talent?.fullname?.charAt(0).toUpperCase() +
                          talent?.fullname.slice(1)}{" "}
                        has no work experience yet
                      </h4>
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

// export const getStaticProps = async (context) => {
//   const {
//     query: { slug },
//   } = context;
//   const jobList = await axios.get(
//     `${process.env.NEXT_PUBLIC_API_URL}/v1/user/list`
//   );

//   const convert = jobList?.data?.find((res) => res?.["user.fullname" === slug]);

//   return {
//     props: {
//       jobLists: convert,
//     },
//     revalidate: 1800,
//   };
// };

export const getServerSideProps = async (context) => {
  const {
    query: { id },
  } = context;

  const jobList = await axios.get(
    `${process.env.NEXT_PUBLIC_API_URL}/v1/user/detail/${id}`
  );

  let convert = jobList?.data;

  return {
    props: {
      profile: convert,
    },
  };
};

export default ProfileDetail;
