import React, { useState } from "react";
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import Navbar from "@/components/organisms/Navbar";
import Footer from "@/components/organisms/Footer";
import { TfiLocationPin } from "react-icons/tfi";
import mailLogo from "@/public/images/mail-logo.png";
import instaLogo from "@/public/images/instagram.svg";
import githubLogo from "@/public/images/github-logo.svg";
import gitlabLogo from "@/public/images/gitlab-logo.svg";
import Image from "next/image";
import styles from '@/styles/pages/Slug.module.scss'

const ProfileDetail = (props) => {
  const { profile } = props;
  const router = useRouter();
  const {
    query: { slug },
  } = router;

  return (
    <>
      <Head>
        <title>{slug.charAt(0).toUpperCase() + slug.slice(1)} | Proworld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ background: "#E5E5E5" }}>
        <Navbar />
        <div
          className="container"
          style={{ background: "white", paddingTop: "1%", marginTop: "11%" }}
        >
          <div
            className="rounded-1"
            style={{
              backgroundColor: "#5e50a1",
              height: "210px",
            }}
          >
            <div>
              <img
                src={profile?.["user.photo_profile"]}
                style={{
                  width: "170px",
                  marginLeft: "92px",
                  marginTop: "116px",
                  borderRadius: "50%",
                }}
              />
            </div>
          </div>
          <div style={{ marginTop: "94px", marginLeft: "95px" }}>
            <h2>
              {profile?.["user.fullname"]?.charAt(0)?.toUpperCase() +
                profile?.["user.fullname"]?.slice(1)}
            </h2>
            <p style={{ marginTop: "15px" }}>
              {profile?.job.charAt(0).toUpperCase() + profile?.job?.slice(1)}
            </p>
            <div
              className="d-flex"
              style={{ marginBottom: "-6px", gap: "8px" }}
            >
              <TfiLocationPin />
              <p style={{ marginTop: "-5px", color: "#9EA0A5" }}>
                {profile?.domicile?.charAt(0).toUpperCase() +
                  profile?.domicile?.slice(1)}
              </p>
            </div>
            <div>
              <p style={{ color: "#9EA0A5", width: "90%" }}>
                My name is Louis Hitler. I graduated from elementary school
                teacher education at the Indonesian National Education
                University (UPI). I did my internship at a private elementary
                school for 8 months. I am currently very excited about finding a
                teaching position for the upcoming school year. I have several
                lesson plans that I made during my internship. I believe, I will
                be very suitable for class opening at your school.
                {/* .charAt(0).toUpperCase() + profile?.domicile?.slice(1) */}
              </p>
            </div>
            <div style={{display: "flex", justifyContent: "center"}}>
              <button
                className="btn btn-primary"
                style={{ width: "33%", height: "55px", marginTop: "12px" }}
              >
                Hire
              </button>
            </div>
            <div>
              <h2 style={{ marginTop: "40px" }}>Skill</h2>
              <div className="d-flex" style={{ width: "90%" }}>
                <div className="row">
                  {profile?.skills?.map((_item) => (
                    <div className="col-3">
                      <span
                        class={"badge bg-warning"}
                        style={{
                          marginTop: "10px",
                          marginRight: "12px",
                          height: "40px",
                          width: "95px",
                          padding: "13px",
                        }}
                        key={_item}
                      >
                        {_item}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <div>
              <div style={{ display: "flex", marginTop: "35px" }}>
                <Image
                  src={mailLogo}
                  alt="Mail"
                  style={{ width: "47px", height: "40px", marginTop: "6px" }}
                />
                <p
                  style={{
                    marginTop: "10px",
                    marginLeft: "20px",
                    color: "#9EA0A5",
                  }}
                >
                  talent@gmail.com
                </p>
              </div>
              <div style={{ display: "flex", marginTop: "12px" }}>
                <Image
                  src={instaLogo}
                  alt="Instagram"
                  style={{ width: "50px", height: "40px" }}
                />
                <p
                  style={{
                    marginTop: "7px",
                    marginLeft: "20px",
                    color: "#9EA0A5",
                  }}
                >
                  louis.hitler_911
                </p>
              </div>
              <div style={{ display: "flex", marginTop: "12px" }}>
                <Image
                  src={githubLogo}
                  alt="Github"
                  style={{ width: "50px", height: "40px" }}
                />
                <p
                  style={{
                    marginTop: "7px",
                    marginLeft: "20px",
                    color: "#9EA0A5",
                  }}
                >
                  louis.hitler
                </p>
              </div>
              <div style={{ display: "flex", marginTop: "12px" }}>
                <Image
                  src={gitlabLogo}
                  alt="Gitlab"
                  style={{ width: "50px", height: "40px" }}
                />
                <p
                  style={{
                    marginTop: "7px",
                    marginLeft: "20px",
                    color: "#9EA0A5",
                  }}
                >
                  louis.hitler
                </p>
              </div>
            </div>
            <div style={{ marginTop: "45px" }}>
              <ul class="nav nav-tabs">
                <li class="nav-item">
                  <button class="nav-link text-dark" id="nav-portfolio-tab" data-bs-toggle="tab" data-bs-target="#nav-portfolio" type="button" role="tab" aria-controls="nav-portfolio" aria-selected="true">
                    Portofolio
                  </button>
                </li>
                <li class="nav-item">
                  <button class="nav-link text-dark" id="nav-experience-tab" data-bs-toggle="tab" data-bs-target="#nav-experience" type="button" role="tab" aria-controls="nav-experience" aria-selected="false">
                    Work Experience
                  </button>
                </li>
              </ul>
              <div class="tab-content" id="nav-tabContent">
                <div className="tab-pane fade show" id="nav-portfolio" role="tabpanel" aria-labelledby="nav-portfolio-tab">

                  <div className="row">
                    <div className="col-3">
                      <img
                        src="https://images.tokopedia.net/img/helpcenter/%7B2022%7D/%7B12%7D/gabung-keanggotaan-toko-power-merchant-tokopedia.png"
                        style={{
                          width: "175px",
                          height: "100px",
                          marginTop: "35px",
                          padding: "1px",
                          border: "2px solid #5E50A1",
                          objectFit: "cover",
                        }}
                      />
                      <p
                        style={{
                          textAlign: "center",
                          paddingRight: "60px",
                          paddingTop: "5px",
                        }}
                      >
                        Tokopedia
                      </p>
                    </div>
                    <div className="col-3">
                      <img
                        src="https://cdn.teknobgt.com/wp-content/shopee-web.png.webp"
                        style={{
                          width: "175px",
                          height: "100px",
                          marginTop: "35px",
                          padding: "1px",
                          border: "2px solid #5E50A1",
                          objectFit: "cover",
                        }}
                      />
                      <p
                        style={{
                          textAlign: "center",
                          paddingRight: "60px",
                          paddingTop: "5px",
                        }}
                      >
                        Shopee
                      </p>
                    </div>
                    <div className="col-3">
                      <img
                        src="https://itemku.zendesk.com/hc/article_attachments/360067565492/Cek_Riwayat_Pesanan_itemku_web_5.png"
                        style={{
                          width: "175px",
                          height: "100px",
                          marginTop: "35px",
                          padding: "1px",
                          border: "2px solid #5E50A1",
                          objectFit: "cover",
                        }}
                      />
                      <p
                        style={{
                          textAlign: "center",
                          paddingRight: "60px",
                          paddingTop: "5px",
                        }}
                      >
                        Itemku
                      </p>
                    </div>
                    <div className="col-3">
                      <img
                        src="https://d26bwjyd9l0e3m.cloudfront.net/wp-content/uploads/2014/11/header-codashop.jpg"
                        style={{
                          width: "175px",
                          height: "100px",
                          marginTop: "35px",
                          padding: "1px",
                          border: "2px solid #5E50A1",
                          objectFit: "cover",
                        }}
                      />
                      <p
                        style={{
                          textAlign: "center",
                          paddingRight: "60px",
                          paddingTop: "5px",
                        }}
                      >
                        Codashop
                      </p>
                    </div>
                    <div className="col-3">
                      <img
                        src="https://blog.unipin.com/wp-content/uploads/2021/04/unipin-1024x702.png"
                        style={{
                          width: "175px",
                          height: "100px",
                          marginTop: "35px",
                          padding: "1px",
                          border: "2px solid #5E50A1",
                          objectFit: "cover",
                        }}
                      />
                      <p
                        style={{
                          textAlign: "center",
                          paddingRight: "60px",
                          paddingTop: "5px",
                        }}
                      >
                        Unipin
                      </p>
                    </div>
                  </div>
                </div>
                <div className="tab-pane fade show" id="nav-experience" role="tabpanel" aria-labelledby="nav-experience-tab">
                  test
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export const getServerSideProps = async (context) => {
  const {
    query: { slug },
  } = context;
  const jobList = await axios.get(
    `${process.env.NEXT_PUBLIC_WEB}/api/talentData`
  );
  console.log(jobList);
  const convert = jobList.data?.find((res) => res?.["user.fullname"] === slug);

  return {
    props: {
      profile: convert,
    },
  };
};

export default ProfileDetail;
