import Head from "next/head";
import axios from "axios";
import React, { useEffect } from "react";
import styles from "../../styles/pages/Auth.module.scss";
import { useRouter } from "next/router";
import LeftColumn from "@/components/molecules/LeftColumnLogReg";
import Link from "next/link";

const Recruiter = () => {
  return (
    <>
      <Head>
        <title>Home | Proworld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="row">
          <div className="col-lg-6 col-xs-12">
            <LeftColumn />
          </div>
          <div className="col-lg-6">
            <div className={styles.welcome}>
              <h1 style={{ marginBottom: "60px" }}>Welcome to Proworld !</h1>
              <p style={{ fontSize: "22px" }}>Please choose your role</p>
            </div>
            <div className={styles.content}>
              <div
                className="modal fade"
                id="talent"
                aria-hidden="true"
                aria-labelledby="exampleModalToggleLabel"
                tabindex="-1"
              >
                <div className="modal-dialog modal-dialog-centered modal-sm">
                  <div className="modal-content">
                    <div className="modal-header">
                      <h1
                        className="modal-title fs-5"
                        id="exampleModalToggleLabel"
                      >
                        Select an option below
                      </h1>
                      <button
                        type="button"
                        className="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"
                      ></button>
                    </div>
                    <div
                      className="modal-body"
                      style={{ display: "flex", justifyContent: "center" }}
                    >
                      <a href="/auth/register">
                        <button
                          className="btn btn-primary"
                          style={{ marginRight: "50px" }}
                        >
                          Register
                        </button>
                      </a>
                      <a href="/auth/login">
                        <button className="btn btn-primary">Login</button>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <a
                className="btn btn-primary"
                data-bs-toggle="modal"
                href="#talent"
                role="button"
              >
                As Talent
              </a>
              <h4>or</h4>
              <div
                className="modal fade"
                id="recruiter"
                aria-hidden="true"
                aria-labelledby="exampleModalToggleLabel"
                tabindex="-1"
              >
                <div className="modal-dialog modal-dialog-centered modal-sm">
                  <div className="modal-content">
                    <div className="modal-header">
                      <h1
                        className="modal-title fs-5"
                        id="exampleModalToggleLabel"
                      >
                        Select an option below
                      </h1>
                      <button
                        type="button"
                        className="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"
                      ></button>
                    </div>
                    <div className="modal-body d-flex justify-content-center">
                      <a href="/auth/register/recruiter">
                        <button
                          className="btn btn-primary"
                          style={{ marginRight: "50px" }}
                        >
                          Register
                        </button>
                      </a>
                      <a href="/auth/login">
                        <button className="btn btn-primary">Login</button>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <a
                className="btn btn-primary"
                data-bs-toggle="modal"
                href="#recruiter"
                role="button"
              >
                As Recruiter
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Recruiter;
