import Head from "next/head";
import Image from "next/image"; 
import Link from "next/link";
import axios from "axios";
import React from "react";
import style from "../../styles/pages/Auth.module.scss";
import proworldLogo from '@/public/images/proworld-logo.png'

const Recruiter = () => {
  return (
    <>
    <Head>
        <title>Recruiter Register | Proworld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={style.main}>
      <div className="row">
        <div className={"col-lg-6"}>
          <div className={style.leftCol}>
            <div className={style.overlay} />
            <div className={style.content}>
              <div className={style.appLogo}>
               <Image src={proworldLogo}/>
              </div>
              <h1 className={style.sloganText}>
              Find the best & talented developers in various fields of expertise
              </h1>
            </div>
          </div>
        </div>
        <div className="col-lg-6">
          <div className={style.loginForm}>
            <Link href="/auth/login/recruiter" >
              <button
                type="submit"
                className="btn btn-primary btn-lg"
              >
                As recruiter
              </button>
            </Link>
            <p>
              or
            </p>
            <Link href="/auth/login">
              <button
                type="submit"
                className="btn btn-primary btn-lg"
              >
                As talent
              </button>
            </Link>
          </div>
        </div>
      </div>  
    </main>
    </>
  );
}

export default Recruiter;
