import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/pages/Home.module.scss";
import Link from "next/link";
import Navbar from "@/components/organisms/Navbar";
import Footer from "@/components/organisms/Footer";
import mainImage from "@/public/images/developer.svg";
import overlayBackground from "@/public/images/sloping-square.svg";
import polkadot from "@/public/images/polkadot.svg";
import { useState } from "react";
import { getCookie } from "cookies-next";
import { useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

const Home = () => {
  const profile = useSelector((state) => state.auth);

  const isLogin = profile?.profile?.payload;

  return (
    <>
      <Head>
        <title>Home | Proworld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />

        <div className="container" style={{ zIndex: 1 }}>
          <div className="row align-items-center">
            {/* <!-- side left --> */}
            <div className="col-lg-5 col-xs-12">
              <h1 style={{ fontSize: "45px" }}>
                The nation&apos;s best talent for revolution change 2.0
              </h1>
              <p
                style={{
                  marginTop: "1rem",
                  marginBottom: "2rem",
                  fontSize: "20px",
                  color: "#46505C",
                }}
              >
                We provide Talents and skills that you can rely on, interested?
                Click the button below
              </p>
              <Link href={`${isLogin ? "/jobs" : "/auth"}`}>
                <button
                  className="btn btn-primary"
                  style={{
                    height: "50px",
                    width: "170px",
                    borderRadius: "3px",
                  }}
                >
                  Start from now
                </button>
              </Link>
            </div>
            {/* <!-- side right --> */}
            <div className={`col-lg-6 ${styles.backgroundGrid}`}>
              <Image
                unoptimized={true}
                src={mainImage}
                className={styles.mainBackground}
                alt="Developer"
              />
              {/* <!-- background header --> */}
              <Image
                unoptimized={true}
                src={overlayBackground}
                className={styles.background1}
                alt="Background"
              />
              <Image
                unoptimized={true}
                src={polkadot}
                className={styles.background2}
                alt="Polkadot"
              />
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Home;
