import React from "react";
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";

const ProfileDetail = (props) => {
  const { profile } = props;
  const router = useRouter();
  const {
    query: { slug },
  } = router;

  return (
    <>
      <Head>
        <title>{ slug } | Proworld</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = async (context) => {
  const {
    query: { slug },
  } = context;
  const jobList = await axios.get(
    `${process.env.NEXT_PUBLIC_WEB}/api/talentData`
  );
  console.log(jobList)
  const convert = jobList.data?.find((res) => res.slug === slug);

  return {
    props: {
      profile: convert,
    }, // will be passed to the page component as props
  };
}